<h2>RGB Fenster</h2>
04.11.2009 - 13:06<p>
Hierso beim Abwaschen in der K&uuml;che, f&auml;llt mir doch auf, das was fehlt... ich brauch hier eigentlich ein Fenster... so Acrylglas mit der Hood drauf raufgemalt und rgb LEDs hinter... das w&auml;r mal geil...