<h2>Was bau ich als nächstes?</h2>
20.10.2009 - 16:33<p>
Mein RC-5 Fernbedienungsding scheiterte ja schon an der Beschaltung einer IR Diode... ich brauche was einfaches... oder ein Bredboard... zum rumstecken, löten geht so auf die Atemwege....
